name: Deploy to pypi
on:
    release:
        types: [published]
jobs:
    build-container:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./
        steps:
            - uses: actions/checkout@v4
            - name: Set up python
              uses: actions/setup-python@v4
              with:
                python-version: "3.11"
            - name: Install requirements
              run: >-
                pip install -r requirements.txt
            - name: Run tests
              run: >-
                pytest ./tests/*
            - name: Build package
              run: >-
                python setup.py sdist
            - name: Upload to pypi
              run: >-
                twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}
